language: java

branches:
  only:
  - master
  - /^feature-.*$/
  
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

#  to avoid uploading the cache after every build
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  email:
    on_success: never # default: change

deploy:
  provider: heroku
  app: mentoring-project-deployment
  api_key:
    secure: "daa566b5-b7cf-4071-aa30-ce16b6df814e"
  on: feature-03-CI-CD